# Generated by Django 3.0.5 on 2020-06-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('image_2', models.FileField(upload_to='')),
                ('image_3', models.FileField(upload_to='')),
                ('price', models.FloatField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('facility_type', models.CharField(choices=[('L', 'Land'), ('A', 'Apartment'), ('R', 'Rental')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='main.Vendor')),
            ],
        ),
    ]
